import { useState } from 'react';
import { QuestionMarkCircleIcon } from '@heroicons/react/outline';
import Modal from './Modal';
import Link from './Link';

function About() {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  return (
    <div className="flex justify-center align-middle items-center">
      <button
        type="button"
        className="inline-flex justify-center text-sm font-medium"
        onClick={() => setIsOpen(true)}
      >
        <QuestionMarkCircleIcon className="w-5 h-5 sm:w-10 sm:h-10" />
      </button>

      <Modal title="ABOUT" isOpen={isOpen} setIsOpen={setIsOpen}>
        <div className="text-lg">
          BASTARD GAN PUNKS are a collection of NFTs generated by applying a GAN on the original set of CRYPTOPUNKS.
          ALLBASTARDS.COM displays the entire bastard collection.
          Learn more about BASTARD GAN PUNKS at <Link to="https://bastardganpunks.club/" text="BASTARDGANPUNKS.CLUB" />.
        </div>
      </Modal>
    </div>
  );
}

export default About;
